language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install flake8 --use-mirrors
  - pip install git+https://github.com/quamilek/bob-ajax-selects.git@develop
  - pip install git+https://github.com/allegro/django-bob.git@develop
  - pip install git+https://github.com/allegro/ralph.git@develop --allow-all-external --allow-unverified ipaddr --allow-unverified postmarkup --allow-unverified python-graph-core --allow-unverified pysphere
  - pip install git+https://github.com/allegro/ralph_assets.git@release/1.4.2
  - pip install . --use-mirrors
before_script:
  - flake8 --exclude="migrations" --statistics src/ralph_pricing
# command to run tests, e.g. python setup.py test
script: DJANGO_SETTINGS_PROFILE=test-pricing ralph test ralph_pricing
