language: python
env:
  matrix:
    - DJANGO_VERSION=1.4.17 TEST_DATABASE_ENGINE=mysql
    - DJANGO_VERSION=1.4.17 TEST_DATABASE_ENGINE=sqlite
    - DJANGO_VERSION=1.6.9 TEST_DATABASE_ENGINE=sqlite
matrix:
  allow_failures:
    - env: DJANGO_VERSION=1.4.17 TEST_DATABASE_ENGINE=sqlite
    - env: DJANGO_VERSION=1.6.9 TEST_DATABASE_ENGINE=sqlite
python:
  - "2.7"
cache:
  directories:
  - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install git+https://github.com/quamilek/bob-ajax-selects.git@develop
  - pip install git+https://github.com/allegro/django-bob.git@develop
  - pip install git+https://github.com/zefciu/django-search-forms@develop
  - pip install git+https://github.com/allegro/ralph_assets.git@develop
  - pip install git+https://github.com/allegro/ralph.git@develop --allow-all-external --allow-unverified ipaddr --allow-unverified postmarkup --allow-unverified python-graph-core --allow-unverified pysphere
  - pip install coveralls
  - pip install . --use-mirrors
before_install:
  - pip install flake8 --use-mirrors
  - make flake
before_script:
  mysql -e 'CREATE DATABASE ralph CHARACTER SET utf8 COLLATE utf8_general_ci;'
# command to run tests, e.g. python setup.py test
script:
  make test-with-coveralls
after_success:
  coveralls
